set_property SRC_FILE_INFO {cfile:C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/io.xdc rfile:../../../../constraint/io.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/pblock.xdc rfile:../../../../constraint/pblock.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/timing.xdc rfile:../../../../constraint/timing.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports EXTCLK50M]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports EEPROM_CS]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports EEPROM_SK]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports EEPROM_DI]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports EEPROM_DO]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports ETH_RSTn]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3 [get_ports ETH_TX_CLK]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports ETH_TX_EN]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ETH_TXD[0]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ETH_TXD[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {ETH_TXD[2]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {ETH_TXD[3]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports ETH_TX_ER]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports ETH_RX_CLK]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports ETH_RX_DV]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {ETH_RXD[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ETH_RXD[1]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ETH_RXD[2]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ETH_RXD[3]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports ETH_RX_ER]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports ETH_CRS]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports ETH_COL]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T2 [get_ports ETH_MDC]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports ETH_MDIO]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports EASIROC1_HOLDB]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports EASIROC1_RESET_PA]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports EASIROC1_PWR_ON]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports EASIROC1_VAL_EVT]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports EASIROC1_RAZ_CHN]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B25 [get_ports EASIROC1_CLK_SR]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24 [get_ports EASIROC1_RSTB_SR]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25 [get_ports EASIROC1_SRIN_SR]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports EASIROC1_LOAD_SC]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports EASIROC1_SELECT_SC]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C23 [get_ports EASIROC1_CLK_READ]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24 [get_ports EASIROC1_RSTB_READ]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A23 [get_ports EASIROC1_SRIN_READ]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J26 [get_ports EASIROC1_ADC_CLK_HG]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {EASIROC1_ADC_DATA_HG[0]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {EASIROC1_ADC_DATA_HG[1]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {EASIROC1_ADC_DATA_HG[2]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E26 [get_ports {EASIROC1_ADC_DATA_HG[3]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F24 [get_ports {EASIROC1_ADC_DATA_HG[4]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports {EASIROC1_ADC_DATA_HG[5]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G24 [get_ports {EASIROC1_ADC_DATA_HG[6]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports {EASIROC1_ADC_DATA_HG[7]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26 [get_ports {EASIROC1_ADC_DATA_HG[8]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24 [get_ports {EASIROC1_ADC_DATA_HG[9]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26 [get_ports {EASIROC1_ADC_DATA_HG[10]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J24 [get_ports {EASIROC1_ADC_DATA_HG[11]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J25 [get_ports EASIROC1_ADC_OTR_HG]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports EASIROC1_ADC_CLK_LG]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {EASIROC1_ADC_DATA_LG[0]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {EASIROC1_ADC_DATA_LG[1]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {EASIROC1_ADC_DATA_LG[2]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {EASIROC1_ADC_DATA_LG[3]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {EASIROC1_ADC_DATA_LG[4]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {EASIROC1_ADC_DATA_LG[5]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {EASIROC1_ADC_DATA_LG[6]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {EASIROC1_ADC_DATA_LG[7]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {EASIROC1_ADC_DATA_LG[8]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {EASIROC1_ADC_DATA_LG[9]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {EASIROC1_ADC_DATA_LG[10]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports {EASIROC1_ADC_DATA_LG[11]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports EASIROC1_ADC_OTR_LG]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[0]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[1]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[2]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[3]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[4]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[5]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[6]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[7]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[8]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[9]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[10]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_HG[11]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[0]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[1]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[2]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[3]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[4]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[5]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[6]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[7]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[8]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[9]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[10]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC1_ADC_DATA_LG[11]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports EASIROC1_ADC_OTR_HG]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports EASIROC1_ADC_OTR_LG]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T25 [get_ports {EASIROC1_TRIGGER[0]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T24 [get_ports {EASIROC1_TRIGGER[1]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T23 [get_ports {EASIROC1_TRIGGER[2]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R26 [get_ports {EASIROC1_TRIGGER[3]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R25 [get_ports {EASIROC1_TRIGGER[4]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R23 [get_ports {EASIROC1_TRIGGER[5]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P26 [get_ports {EASIROC1_TRIGGER[6]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P25 [get_ports {EASIROC1_TRIGGER[7]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P24 [get_ports {EASIROC1_TRIGGER[8]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P23 [get_ports {EASIROC1_TRIGGER[9]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N26 [get_ports {EASIROC1_TRIGGER[10]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N24 [get_ports {EASIROC1_TRIGGER[11]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N23 [get_ports {EASIROC1_TRIGGER[12]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M26 [get_ports {EASIROC1_TRIGGER[13]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M25 [get_ports {EASIROC1_TRIGGER[14]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24 [get_ports {EASIROC1_TRIGGER[15]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L25 [get_ports {EASIROC1_TRIGGER[16]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L24 [get_ports {EASIROC1_TRIGGER[17]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L23 [get_ports {EASIROC1_TRIGGER[18]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L22 [get_ports {EASIROC1_TRIGGER[19]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K26 [get_ports {EASIROC1_TRIGGER[20]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K25 [get_ports {EASIROC1_TRIGGER[21]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {EASIROC1_TRIGGER[22]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports {EASIROC1_TRIGGER[23]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R20 [get_ports {EASIROC1_TRIGGER[24]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports {EASIROC1_TRIGGER[25]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports {EASIROC1_TRIGGER[26]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports {EASIROC1_TRIGGER[27]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports {EASIROC1_TRIGGER[28]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports {EASIROC1_TRIGGER[29]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {EASIROC1_TRIGGER[30]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {EASIROC1_TRIGGER[31]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports EASIROC2_HOLDB]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports EASIROC2_RESET_PA]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports EASIROC2_PWR_ON]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports EASIROC2_VAL_EVT]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports EASIROC2_RAZ_CHN]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports EASIROC2_CLK_SR]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports EASIROC2_RSTB_SR]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports EASIROC2_SRIN_SR]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports EASIROC2_LOAD_SC]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports EASIROC2_SELECT_SC]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports EASIROC2_CLK_READ]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports EASIROC2_RSTB_READ]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports EASIROC2_SRIN_READ]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports EASIROC2_ADC_CLK_HG]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports {EASIROC2_ADC_DATA_HG[0]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports {EASIROC2_ADC_DATA_HG[1]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports {EASIROC2_ADC_DATA_HG[2]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports {EASIROC2_ADC_DATA_HG[3]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {EASIROC2_ADC_DATA_HG[4]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {EASIROC2_ADC_DATA_HG[5]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {EASIROC2_ADC_DATA_HG[6]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {EASIROC2_ADC_DATA_HG[7]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {EASIROC2_ADC_DATA_HG[8]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {EASIROC2_ADC_DATA_HG[9]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E5 [get_ports {EASIROC2_ADC_DATA_HG[10]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {EASIROC2_ADC_DATA_HG[11]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports EASIROC2_ADC_OTR_HG]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports EASIROC2_ADC_CLK_LG]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {EASIROC2_ADC_DATA_LG[0]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3 [get_ports {EASIROC2_ADC_DATA_LG[1]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {EASIROC2_ADC_DATA_LG[2]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports {EASIROC2_ADC_DATA_LG[3]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {EASIROC2_ADC_DATA_LG[4]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {EASIROC2_ADC_DATA_LG[5]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {EASIROC2_ADC_DATA_LG[6]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {EASIROC2_ADC_DATA_LG[7]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {EASIROC2_ADC_DATA_LG[8]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {EASIROC2_ADC_DATA_LG[9]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {EASIROC2_ADC_DATA_LG[10]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {EASIROC2_ADC_DATA_LG[11]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports EASIROC2_ADC_OTR_LG]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[0]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[1]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[2]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[3]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[4]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[5]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[6]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[7]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[8]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[9]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[10]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_HG[11]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[0]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[1]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[2]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[3]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[4]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[5]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[6]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[7]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[8]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[9]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[10]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {EASIROC2_ADC_DATA_LG[11]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports EASIROC2_ADC_OTR_HG]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports EASIROC2_ADC_OTR_LG]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U24 [get_ports {EASIROC2_TRIGGER[0]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U25 [get_ports {EASIROC2_TRIGGER[1]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U26 [get_ports {EASIROC2_TRIGGER[2]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V24 [get_ports {EASIROC2_TRIGGER[3]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V26 [get_ports {EASIROC2_TRIGGER[4]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W24 [get_ports {EASIROC2_TRIGGER[5]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W25 [get_ports {EASIROC2_TRIGGER[6]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W26 [get_ports {EASIROC2_TRIGGER[7]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y25 [get_ports {EASIROC2_TRIGGER[8]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y26 [get_ports {EASIROC2_TRIGGER[9]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA25 [get_ports {EASIROC2_TRIGGER[10]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB26 [get_ports {EASIROC2_TRIGGER[11]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC26 [get_ports {EASIROC2_TRIGGER[12]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB25 [get_ports {EASIROC2_TRIGGER[13]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA24 [get_ports {EASIROC2_TRIGGER[14]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB24 [get_ports {EASIROC2_TRIGGER[15]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC24 [get_ports {EASIROC2_TRIGGER[16]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W23 [get_ports {EASIROC2_TRIGGER[17]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y23 [get_ports {EASIROC2_TRIGGER[18]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA23 [get_ports {EASIROC2_TRIGGER[19]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y22 [get_ports {EASIROC2_TRIGGER[20]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {EASIROC2_TRIGGER[21]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports {EASIROC2_TRIGGER[22]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {EASIROC2_TRIGGER[23]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports {EASIROC2_TRIGGER[24]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {EASIROC2_TRIGGER[25]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {EASIROC2_TRIGGER[26]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {EASIROC2_TRIGGER[27]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {EASIROC2_TRIGGER[28]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports {EASIROC2_TRIGGER[29]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {EASIROC2_TRIGGER[30]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {EASIROC2_TRIGGER[31]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {DIP_SW[0]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports SPI_SCLK]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports SPI_SS_N]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports SPI_MOSI]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R15 [get_ports SPI_MISO]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports PROG_B_ON]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports SPI_SCLK]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports SPI_SS_N]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports SPI_MOSI]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports SPI_MISO]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports PROG_B_ON]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {LED[1]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {LED[2]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {LED[3]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {LED[4]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {LED[5]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {LED[6]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {LED[7]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {LED[8]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports CAL1]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports CAL2]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports PWR_RST]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {MUX[0]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports {MUX[1]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports {MUX[2]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {MUX[3]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {MUX_EN[0]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports {MUX_EN[1]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {MUX_EN[2]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports {MUX_EN[3]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6 [get_ports CS_MADC]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports DIN_MADC]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports SCK_MADC]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports DOUT_MADC]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {ETH_LED[1]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {ETH_LED[2]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7 [get_ports SCK_DAC]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports SDI_DAC]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports CS_DAC]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports HV_EN]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {IN_FPGA[1]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R22 [get_ports {IN_FPGA[2]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21 [get_ports {IN_FPGA[3]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P21 [get_ports {IN_FPGA[4]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N21 [get_ports {IN_FPGA[5]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21 [get_ports {IN_FPGA[6]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {OUT_FPGA[1]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {OUT_FPGA[2]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {OUT_FPGA[3]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {OUT_FPGA[4]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {OUT_FPGA[5]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports OR32_C1]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports OR32_C2]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports DIGITAL_LINE_C1]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports DIGITAL_LINE_C2]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_Scaler_DB_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_Scaler_DB_SyncRptr0] [get_cells -quiet [list {Scaler_0/DoubleBuffer_0/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {Scaler_0/DoubleBuffer_0/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_Scaler_DB_SyncRptr0] -add {SLICE_X10Y154:SLICE_X11Y155}
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_Scaler_DB_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_Scaler_DB_SyncRptr1] [get_cells -quiet [list {Scaler_0/DoubleBuffer_0/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {Scaler_0/DoubleBuffer_0/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_Scaler_DB_SyncRptr1] -add {SLICE_X10Y149:SLICE_X11Y149}
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_Scaler_DB_SyncWprt0
add_cells_to_pblock [get_pblocks pblock_Scaler_DB_SyncWprt0] [get_cells -quiet [list {Scaler_0/DoubleBuffer_0/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {Scaler_0/DoubleBuffer_0/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_Scaler_DB_SyncWprt0] -add {SLICE_X14Y156:SLICE_X15Y156}
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_Scaler_DB_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_Scaler_DB_SyncWptr1] [get_cells -quiet [list {Scaler_0/DoubleBuffer_0/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {Scaler_0/DoubleBuffer_0/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_Scaler_DB_SyncWptr1] -add {SLICE_X22Y154:SLICE_X23Y154}
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG1_DB_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_ADCHG1_DB_SyncRptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG1_DB_SyncRptr0] -add {SLICE_X20Y155:SLICE_X21Y156}
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG1_DB_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_ADCHG1_DB_SyncRptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG1_DB_SyncRptr1] -add {SLICE_X18Y159:SLICE_X19Y159}
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG1_DB_SyncWptr0
add_cells_to_pblock [get_pblocks pblock_ADCHG1_DB_SyncWptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG1_DB_SyncWptr0] -add {SLICE_X18Y157:SLICE_X19Y158}
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG1_DB_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_ADCHG1_DB_SyncWptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG1/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG1_DB_SyncWptr1] -add {SLICE_X16Y159:SLICE_X17Y160}
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG2_DB_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_ADCHG2_DB_SyncRptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG2_DB_SyncRptr0] -add {SLICE_X20Y159:SLICE_X21Y160}
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG2_DB_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_ADCHG2_DB_SyncRptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG2_DB_SyncRptr1] -add {SLICE_X14Y150:SLICE_X15Y151}
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG2_DB_SyncWptr0
add_cells_to_pblock [get_pblocks pblock_ADCHG2_DB_SyncWptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG2_DB_SyncWptr0] -add {SLICE_X16Y154:SLICE_X17Y155}
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCHG2_DB_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_ADCHG2_DB_SyncWptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_HG2/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCHG2_DB_SyncWptr1] -add {SLICE_X14Y144:SLICE_X15Y145}
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG1_DB_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_ADCLG1_DB_SyncRptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG1_DB_SyncRptr0] -add {SLICE_X14Y141:SLICE_X15Y142}
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG1_DB_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_ADCLG1_DB_SyncRptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG1_DB_SyncRptr1] -add {SLICE_X18Y154:SLICE_X19Y154}
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG1_DB_SyncWptr0
add_cells_to_pblock [get_pblocks pblock_ADCLG1_DB_SyncWptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG1_DB_SyncWptr0] -add {SLICE_X14Y153:SLICE_X15Y154}
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG1_DB_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_ADCLG1_DB_SyncWptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG1/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG1_DB_SyncWptr1] -add {SLICE_X18Y150:SLICE_X19Y150}
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG2_DB_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_ADCLG2_DB_SyncRptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG2_DB_SyncRptr0] -add {SLICE_X16Y156:SLICE_X17Y157}
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG2_DB_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_ADCLG2_DB_SyncRptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG2_DB_SyncRptr1] -add {SLICE_X20Y152:SLICE_X21Y152}
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG2_DB_SyncWptr0
add_cells_to_pblock [get_pblocks pblock_ADCLG2_DB_SyncWptr0] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG2_DB_SyncWptr0] -add {SLICE_X22Y156:SLICE_X23Y157}
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ADCLG2_DB_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_ADCLG2_DB_SyncWptr1] [get_cells -quiet [list {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {ADC_0/ADC_EventBuffer_LG2/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_ADCLG2_DB_SyncWptr1] -add {SLICE_X22Y152:SLICE_X23Y152}
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBL_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_TDC_EBL_SyncRptr0] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBL_SyncRptr0] -add {SLICE_X10Y142:SLICE_X11Y143}
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBL_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_TDC_EBL_SyncRptr1] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBL_SyncRptr1] -add {SLICE_X16Y150:SLICE_X17Y150}
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBL_SyncWptr0
add_cells_to_pblock [get_pblocks pblock_TDC_EBL_SyncWptr0] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBL_SyncWptr0] -add {SLICE_X14Y147:SLICE_X15Y148}
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBL_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_TDC_EBL_SyncWptr1] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Leading/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBL_SyncWptr1] -add {SLICE_X12Y155:SLICE_X13Y155}
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBT_SyncRptr0
add_cells_to_pblock [get_pblocks pblock_TDC_EBT_SyncRptr0] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Rptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBT_SyncRptr0] -add {SLICE_X10Y145:SLICE_X11Y146}
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBT_SyncRptr1
add_cells_to_pblock [get_pblocks pblock_TDC_EBT_SyncRptr1] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Rptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBT_SyncRptr1] -add {SLICE_X10Y152:SLICE_X11Y152}
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBT_SyncWptr0
add_cells_to_pblock [get_pblocks pblock_TDC_EBT_SyncWptr0] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Wptr/Synchronizer1bit[0].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBT_SyncWptr0] -add {SLICE_X14Y158:SLICE_X15Y159}
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_TDC_EBT_SyncWptr1
add_cells_to_pblock [get_pblocks pblock_TDC_EBT_SyncWptr1] [get_cells -quiet [list {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF1} {MHTDC_0/MHTDC_EventBuffer_Trailing/Synchronizer_Wptr/Synchronizer1bit[1].Synchronizer_0/DoubleFFSynchronizerFF2}]]
resize_pblock [get_pblocks pblock_TDC_EBT_SyncWptr1] -add {SLICE_X20Y157:SLICE_X21Y157}
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_L1
add_cells_to_pblock [get_pblocks pblock_SyncEdge_L1] [get_cells -quiet [list TriggerManager_0/SynchEdgeDetector_L1/Synchronizer_0/DoubleFFSynchronizerFF1 TriggerManager_0/SynchEdgeDetector_L1/Synchronizer_0/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_L1] -add {SLICE_X34Y52:SLICE_X35Y53}
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_L2
add_cells_to_pblock [get_pblocks pblock_SyncEdge_L2] [get_cells -quiet [list TriggerManager_0/SynchEdgeDetector_L2/Synchronizer_0/DoubleFFSynchronizerFF1 TriggerManager_0/SynchEdgeDetector_L2/Synchronizer_0/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_L2] -add {SLICE_X38Y50:SLICE_X39Y51}
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_FASTCLEAR
add_cells_to_pblock [get_pblocks pblock_SyncEdge_FASTCLEAR] [get_cells -quiet [list TriggerManager_0/SynchEdgeDetector_FAST_CLEAR/Synchronizer_0/DoubleFFSynchronizerFF1 TriggerManager_0/SynchEdgeDetector_FAST_CLEAR/Synchronizer_0/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_FASTCLEAR] -add {SLICE_X30Y50:SLICE_X31Y51}
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_HOLD
add_cells_to_pblock [get_pblocks pblock_SyncEdge_HOLD] [get_cells -quiet [list TriggerManager_0/SynchEdgeDetector_HOLD/Synchronizer_0/DoubleFFSynchronizerFF1 TriggerManager_0/SynchEdgeDetector_HOLD/Synchronizer_0/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_HOLD] -add {SLICE_X34Y50:SLICE_X35Y51}
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_IsDaq
add_cells_to_pblock [get_pblocks pblock_SyncEdge_IsDaq] [get_cells -quiet [list TriggerManager_0/SynchEdgeDetector_IsDaqMode/Synchronizer_0/DoubleFFSynchronizerFF1 TriggerManager_0/SynchEdgeDetector_IsDaqMode/Synchronizer_0/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_IsDaq] -add {SLICE_X36Y50:SLICE_X37Y51}
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_AdcTdcBusy
add_cells_to_pblock [get_pblocks pblock_SyncEdge_AdcTdcBusy] [get_cells -quiet [list TriggerManager_0/Synchronizer_AdcTdcBusy/DoubleFFSynchronizerFF1 TriggerManager_0/Synchronizer_AdcTdcBusy/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_AdcTdcBusy] -add {SLICE_X38Y52:SLICE_X39Y53}
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SyncEdge_GathererBusy
add_cells_to_pblock [get_pblocks pblock_SyncEdge_GathererBusy] [get_cells -quiet [list TriggerManager_0/Synchronizer_GathererBusy/DoubleFFSynchronizerFF1 TriggerManager_0/Synchronizer_GathererBusy/DoubleFFSynchronizerFF2]]
resize_pblock [get_pblocks pblock_SyncEdge_GathererBusy] -add {SLICE_X32Y52:SLICE_X33Y53}
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter EXTCLK50M 0.002
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter ETH_RX_CLK 0.002
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter ETH_TX_CLK 0.002
