# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tfgg676-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/project/project.cache/wt [current_project]
set_property parent.project_path C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/project/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TIMER.v
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SiTCP_XC7A_32K_BBT_V70.v
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/WRAP_SiTCP_GMII_XC7A_32K.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/FineCounterDecoder.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/FineCounter.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/Synchronizer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/package/MHTDC_DataType.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MHTDC_Counter.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/DualPortRam.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/RBCP_Receiver.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TimeWindowRegister.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SynchronizerNbit.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SynchEdgeDetector.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SPI_IF.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SlowControlRegister.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/Serializer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/RBCP_Receiver16bit.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/PulseExtender.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MHTDC_ChannelBuffer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MHTDC_Builder.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/EdgeDetector.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/Delayer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/CommonStopManager.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/package/Asynch.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/Width_Adjuster.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TDC_Gatherer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TCP_Sender_32bit.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SynchFIFO.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SPI_CommandSender.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SlowControl.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SingleScaler.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ScalerGatherer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ReconfigurationManager.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ReadRegister.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MMCM.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MHTDC_Core.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/InterclockTrigger.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/HoldExpander.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/DoubleBuffer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/DFF_1Shot.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/BusyManager.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ADC_Gatherer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ADC_Core.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ADC_Controller.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/shift_reg.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/RBCP_Sender.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MADC_Core.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TriggerDelayer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TestChargeInjection.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/Version.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TriggerWidth.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TriggerManager.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/StatusRegister.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SPI_FLASH_Programmer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SelectableLogic.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ScalerTimer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/Scaler.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ResetManager.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ReadRegisterSelector.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/RBCP_Distributor.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MHTDC.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/GlobalSlowControl.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/GlobalSender.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/GlobalReadRegister.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/GlobalGatherer.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/DiscriOr.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/DirectControl.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ClockManager.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/ADC.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/UsrClkOut.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/package/SynthesizedDate.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/package/RegisterAddress.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/MADC.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/LEDControl.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/HVControl.vhd
  C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/TopLevel.vhd
}
read_edif C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/rtl/SiTCP_XC7A_32K_BBT_V70.ngc
read_xdc C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/constraint/io.xdc
set_property used_in_implementation false [get_files C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/constraint/io.xdc]

read_xdc C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/constraint/timing.xdc
set_property used_in_implementation false [get_files C:/Users/tomoh/vivado/ChikumaProject150923_test191108/chikuma_new/New_Firmware/constraint/timing.xdc]

catch { write_hwdef -file TopLevel.hwdef }
synth_design -top TopLevel -part xc7a100tfgg676-2
write_checkpoint TopLevel.dcp
catch { report_utilization -file TopLevel_utilization_synth.rpt -pb TopLevel_utilization_synth.pb }
