# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {}  -id {Common 17-356}  -string {{ERROR: [Common 17-356] Failed to install all user apps.}}  -suppress 
create_project -in_memory -part xc7a100tfgg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/project/project.cache/wt [current_project]
set_property parent.project_path C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/project/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TIMER.v
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SiTCP_XC7A_32K_BBT_V70.v
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/WRAP_SiTCP_GMII_XC7A_32K.v
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/project/project.srcs/sources_1/imports/rtl/TimingGeneratorModel.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/FineCounterDecoder.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/FineCounter.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/Synchronizer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/RBCP_Receiver.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/package/MHTDC_DataType.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MHTDC_Counter.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/DualPortRam.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TimeWindowRegister.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SynchronizerNbit.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SynchEdgeDetector.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SPI_IF.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SlowControlRegister.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/Serializer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/RBCP_Receiver16bit.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/PulseExtender.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/package/Asynch.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MHTDC_ChannelBuffer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MHTDC_Builder.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/EdgeDetector.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/Delayer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/CommonStopManager.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/project/project.srcs/sources_1/imports/rtl/TriggerDelayer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/Width_Adjuster.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TDC_Gatherer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TCP_Sender_32bit.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SynchFIFO.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SPI_CommandSender.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SlowControl.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SingleScaler.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/shift_reg.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ScalerGatherer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ReconfigurationManager.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ReadRegister.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/RBCP_Sender.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MMCM.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MHTDC_Core.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MADC_Core.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/InterclockTrigger.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/HoldExpander.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/DoubleBuffer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/DFF_1Shot.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/BusyManager.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ADC_Gatherer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ADC_Core.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ADC_Controller.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/Version.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/UsrClkOut.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TriggerWidth.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TriggerManager.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TestChargeInjection.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/StatusRegister.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SPI_FLASH_Programmer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SelectableLogic.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ScalerTimer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/Scaler.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ResetManager.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ReadRegisterSelector.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/RBCP_Distributor.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/package/SynthesizedDate.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/package/RegisterAddress.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MHTDC.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/MADC.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/LEDControl.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/HVControl.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/GlobalSlowControl.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/GlobalSender.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/GlobalReadRegister.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/GlobalGatherer.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/DiscriOr.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/DirectControl.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ClockManager.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/ADC.vhd
  C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/TopLevel.vhd
}
read_edif C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/rtl/SiTCP_XC7A_32K_BBT_V70.ngc
read_xdc C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/io.xdc
set_property used_in_implementation false [get_files C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/io.xdc]

read_xdc C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/pblock.xdc
set_property used_in_implementation false [get_files C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/pblock.xdc]

read_xdc C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/timing.xdc
set_property used_in_implementation false [get_files C:/Users/owner/Downloads/sfgd_vivadoFPGA/EASIROC_FPGA/EASIROC_firmware_NC150923_viva15.3_work2007.fixed200701/constraint/timing.xdc]

synth_design -top TopLevel -part xc7a100tfgg676-2
write_checkpoint -noxdef TopLevel.dcp
catch { report_utilization -file TopLevel_utilization_synth.rpt -pb TopLevel_utilization_synth.pb }
